name: Build and deploy code

on: push

jobs: 
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v4
      - name: Say hi to me
        run: echo "Hi Matthew"