name: Build and deploy code

on: push
  push: 
    branches: ["main"]

jobs: 
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v2
      - name: Say hi to me
        run: echo "Hi Matthew"